In [2]:
####### list vs nd-array (addition)  ###########

import numpy as np


ls2d = [[1,2,3],[4,5,6]]
a2d = np.array(ls2d)

ls2d

[[1, 2, 3], [4, 5, 6]]

In [3]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
####  addition  ####
ls2d_1 = ls2d[::]
a2d_1 = a2d.copy()

ls_add = ls2d + ls2d_1     # appends ls1 and ls2
a_add = a2d + a2d_1        # adds x1 with x2

ls_add  

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [10]:
a_add    

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
#### sqrt ####

np.sqrt(a2d)


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])